start-test: node_modules/restify
	node main.js

node_modules/restify: node_modules

node_modules:
	npm install

start-tested-process:
	@echo "Not implemented"

.PHONY: start-test start-tested-process
